spring:
  application:
    name: cashlendar

  datasource:
    url: jdbc:postgresql://localhost:5432/cashlendar
    username: cashlendar
    password: cashlendar
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/main/changelog.xml
    default-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: public
        format_sql: true
    open-in-view: false

server:
  port: 8080